#!/usr/bin/python
import os
import sys
from getopt import getopt
from comnctl import task, taskList, agentList

def usage():
    # Print all of the options
    print "%s [agent].task" % os.path.basename(sys.argv[0])
    print "Agents:"
    for a in agentList:
        print str(a)
    print ""
    print "Tasks:"
    for t in taskList:
        print str(t)

def call(taskName, agent):
    taskList[taskName](agent)

if __name__ == "__main__":
    ## Look for arguments
    if os.path.isdir('cnctl'):
        # How do I import the directory?
        sys.path.append('.')
        from cnctl import *
    elif os.path.isfile('cnctl.py'):
        # How do I import the file
        sys.path.append('.')
        from cnctl import *
    else:
        print "You must run this in a directory with a cnctl file"
        sys.exit(-1)

    if len(sys.argv) == 1:
        usage()
        sys.exit(0)

    ## Parse the input
    (opts, args) = getopt(sys.argv[1:], "h", ['help', 'dryrun'])
    for o, a in opts:
        if o in ['-h', '--help']:
            usage()
            sys.exit(0)
        elif o in ['--dryrun']:
            # Set dryrun
            pass

    ## Create the dependency list
    tasks = {}
    taskOrder = []
    for a in args:
        try:
            agent, task = a.split('.',1)
        except ValueError:
            agent = ""
            task = a
        if task in taskList.names:
            expanded = taskList[task]._depends
            expanded.append(task)
            for task in expanded:
                if task not in taskOrder:
                    taskOrder.append(task)
                    tasks[task] = []
                else:
                    continue

                if agent in agentList.names:
                    if agentList[agent] not in tasks[task]:
                        tasks[task].append(agentList[agent])
                elif len(agent) == 0:
                    for a in agentList:
                        if a.__type__() == "Agent":
                            if a not in tasks[task]:
                                tasks[task].append(a)
                else:
                    print "cnctl Error: Unknown agent %s" % str(agent)
                    usage()
                    sys.exit(-1)
        else:
            print "cnctl Error: Unknown task: %s" % task
            usage()
            sys.exit(-1)

    for task in taskOrder:
        for agent in tasks[task]:
            call(task, agent)
        for agent in tasks[task]:
            for conn in agent.connection:
                conn.stdin.write('exit\n\0');
                conn.stdin.flush()
                for line in conn.stdout.readlines():
                    agent.out(line.rstrip())
                err = ""
                for line in conn.stderr.readline():
                    if line == '\n':
                        agent.err(err)
                    else:
                        err += line
            agent.connection = None
